line-length = 120

[lint]
select = [
    "E", # Pycodestyle
    "F", # Pyflakes
    "I", # Isort
    "N", # Naming
    "COM", # Commas
    "T", # Print and debugger statements
    "ANN", # Type annotations
    "A", # Builtins shadowing
    "Q", # Quotes
    "RET", # Return statements
    "SIM", # Pieces known to be simplifiable
    "ERA", # Commented out code
    "PL", # Pylint
    "D", # Docstrings
    "PT", # Pytest
]

[lint.pydocstyle]
convention = "google"

[lint.flake8-pytest-style]
parametrize-values-type = "tuple"
parametrize-values-row-type = "tuple"

[lint.per-file-ignores]
"__init__.py" = ["F401"] # Allow unused imports to expose objects.
"__about__.py" = ["D"] # Do not require docstring in this module.
