# This project is implemented exclusively for learning purposes and assumes no commercial use.
# Neither Yury Fedotov nor organizations he is affiliated with claim any rights to the "Ticket to Ride" trademark,
# game rules or other game-related artifacts. "Ticket to Ride" was designed by Alan R. Moon and released
# by Days of Wonder. To the best of author's knowledge, the trademark is owned by Days of Wonder, Inc.
# All rights to the original game and its elements are owned by their respective holders.
# For more information about the game, please visit
# the official Days of Wonder website: https://www.daysofwonder.com/ticket-to-ride/.
"""Default routes for the Europe game version."""
from ticket_to_ride import Color, Route

from .cities import default_cities

default_routes = (
    Route(cities=(default_cities["Edinburgh"], default_cities["London"]), length=4, color=Color.BLACK),
    Route(cities=(default_cities["Edinburgh"], default_cities["London"]), length=4, color=Color.ORANGE),
    Route(cities=(default_cities["London"], default_cities["Dieppe"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["London"], default_cities["Dieppe"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Dieppe"], default_cities["Brest"]), length=2, color=Color.ORANGE),
    Route(cities=(default_cities["Dieppe"], default_cities["Paris"]), length=1, color=Color.PINK),
    Route(cities=(default_cities["Brest"], default_cities["Pamplona"]), length=4, color=Color.PINK),
    Route(cities=(default_cities["Pamplona"], default_cities["Madrid"]), length=3, color=Color.BLACK),
    Route(cities=(default_cities["Pamplona"], default_cities["Madrid"]), length=3, color=Color.WHITE),
    Route(cities=(default_cities["Madrid"], default_cities["Lisboa"]), length=3, color=Color.PINK),
    Route(cities=(default_cities["Lisboa"], default_cities["Cadiz"]), length=2, color=Color.BLUE),
    Route(cities=(default_cities["Cadiz"], default_cities["Madrid"]), length=3, color=Color.ORANGE),
    Route(cities=(default_cities["Madrid"], default_cities["Barcelona"]), length=2, color=Color.YELLOW),
    Route(cities=(default_cities["Barcelona"], default_cities["Pamplona"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Barcelona"], default_cities["Marseille"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Pamplona"], default_cities["Marseille"]), length=4, color=Color.RED),
    Route(cities=(default_cities["Marseille"], default_cities["Paris"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Pamplona"], default_cities["Paris"]), length=4, color=Color.BLUE),
    Route(cities=(default_cities["Pamplona"], default_cities["Paris"]), length=4, color=Color.GREEN),
    Route(cities=(default_cities["Brest"], default_cities["Paris"]), length=3, color=Color.BLACK),
    Route(cities=(default_cities["London"], default_cities["Amsterdam"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Amsterdam"], default_cities["Bruxelles"]), length=1, color=Color.BLACK),
    Route(cities=(default_cities["Bruxelles"], default_cities["Dieppe"]), length=2, color=Color.GREEN),
    Route(cities=(default_cities["Bruxelles"], default_cities["Paris"]), length=2, color=Color.YELLOW),
    Route(cities=(default_cities["Bruxelles"], default_cities["Paris"]), length=2, color=Color.RED),
    Route(cities=(default_cities["Amsterdam"], default_cities["Essen"]), length=3, color=Color.YELLOW),
    Route(cities=(default_cities["Essen"], default_cities["Frankfurt"]), length=2, color=Color.GREEN),
    Route(cities=(default_cities["Amsterdam"], default_cities["Frankfurt"]), length=2, color=Color.WHITE),
    Route(cities=(default_cities["Bruxelles"], default_cities["Frankfurt"]), length=2, color=Color.BLUE),
    Route(cities=(default_cities["Paris"], default_cities["Frankfurt"]), length=3, color=Color.WHITE),
    Route(cities=(default_cities["Paris"], default_cities["Frankfurt"]), length=3, color=Color.ORANGE),
    Route(cities=(default_cities["Frankfurt"], default_cities["Munchen"]), length=2, color=Color.PINK),
    Route(cities=(default_cities["Munchen"], default_cities["Zurich"]), length=2, color=Color.YELLOW),
    Route(cities=(default_cities["Zurich"], default_cities["Paris"]), length=3, color=Color.NEUTRAL),
    Route(cities=(default_cities["Zurich"], default_cities["Marseille"]), length=2, color=Color.PINK),
    Route(cities=(default_cities["Marseille"], default_cities["Roma"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Roma"], default_cities["Venezia"]), length=2, color=Color.BLACK),
    Route(cities=(default_cities["Venezia"], default_cities["Zurich"]), length=2, color=Color.GREEN),
    Route(cities=(default_cities["Venezia"], default_cities["Munchen"]), length=2, color=Color.BLUE),
    Route(cities=(default_cities["Roma"], default_cities["Palermo"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Palermo"], default_cities["Brindisi"]), length=3, color=Color.NEUTRAL),
    Route(cities=(default_cities["Brindisi"], default_cities["Roma"]), length=2, color=Color.WHITE),
    Route(cities=(default_cities["Brindisi"], default_cities["Athena"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Athena"], default_cities["Smyrna"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Palermo"], default_cities["Smyrna"]), length=6, color=Color.NEUTRAL),
    Route(cities=(default_cities["Athena"], default_cities["Sofia"]), length=3, color=Color.PINK),
    Route(cities=(default_cities["Sofia"], default_cities["Saraevo"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Sofia"], default_cities["Bucharest"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Bucharest"], default_cities["Budapest"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Saraevo"], default_cities["Athena"]), length=4, color=Color.GREEN),
    Route(cities=(default_cities["Saraevo"], default_cities["Zagreb"]), length=3, color=Color.RED),
    Route(cities=(default_cities["Saraevo"], default_cities["Budapest"]), length=3, color=Color.PINK),
    Route(cities=(default_cities["Zagreb"], default_cities["Venezia"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Zagreb"], default_cities["Wien"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Zagreb"], default_cities["Budapest"]), length=2, color=Color.ORANGE),
    Route(cities=(default_cities["Wien"], default_cities["Budapest"]), length=1, color=Color.RED),
    Route(cities=(default_cities["Wien"], default_cities["Budapest"]), length=1, color=Color.WHITE),
    Route(cities=(default_cities["Wien"], default_cities["Munchen"]), length=3, color=Color.ORANGE),
    Route(cities=(default_cities["Wien"], default_cities["Berlin"]), length=3, color=Color.GREEN),
    Route(cities=(default_cities["Berlin"], default_cities["Frankfurt"]), length=3, color=Color.BLACK),
    Route(cities=(default_cities["Berlin"], default_cities["Frankfurt"]), length=3, color=Color.RED),
    Route(cities=(default_cities["Berlin"], default_cities["Essen"]), length=2, color=Color.BLUE),
    Route(cities=(default_cities["Essen"], default_cities["København"]), length=3, color=Color.NEUTRAL),
    Route(cities=(default_cities["Essen"], default_cities["København"]), length=3, color=Color.NEUTRAL),
    Route(cities=(default_cities["København"], default_cities["Stockholm"]), length=3, color=Color.WHITE),
    Route(cities=(default_cities["København"], default_cities["Stockholm"]), length=3, color=Color.YELLOW),
    Route(cities=(default_cities["Berlin"], default_cities["Danzic"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Danzic"], default_cities["Warszawa"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Berlin"], default_cities["Warszawa"]), length=4, color=Color.PINK),
    Route(cities=(default_cities["Berlin"], default_cities["Warszawa"]), length=4, color=Color.YELLOW),
    Route(cities=(default_cities["Wien"], default_cities["Warszawa"]), length=4, color=Color.BLUE),
    Route(cities=(default_cities["Warszawa"], default_cities["Kyiv"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Budapest"], default_cities["Kyiv"]), length=6, color=Color.NEUTRAL),
    Route(cities=(default_cities["Bucharest"], default_cities["Kyiv"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Danzic"], default_cities["Riga"]), length=3, color=Color.BLACK),
    Route(cities=(default_cities["Riga"], default_cities["Petrograd"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Stockholm"], default_cities["Petrograd"]), length=8, color=Color.NEUTRAL),
    Route(cities=(default_cities["Petrograd"], default_cities["Wilno"]), length=4, color=Color.BLUE),
    Route(cities=(default_cities["Petrograd"], default_cities["Moskva"]), length=4, color=Color.WHITE),
    Route(cities=(default_cities["Moskva"], default_cities["Smolensk"]), length=2, color=Color.ORANGE),
    Route(cities=(default_cities["Smolensk"], default_cities["Wilno"]), length=3, color=Color.YELLOW),
    Route(cities=(default_cities["Smolensk"], default_cities["Kyiv"]), length=3, color=Color.RED),
    Route(cities=(default_cities["Wilno"], default_cities["Kyiv"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Wilno"], default_cities["Warszawa"]), length=3, color=Color.RED),
    Route(cities=(default_cities["Wilno"], default_cities["Riga"]), length=4, color=Color.GREEN),
    Route(cities=(default_cities["Moskva"], default_cities["Kharkov"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Kyiv"], default_cities["Kharkov"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Kharkov"], default_cities["Rostov"]), length=2, color=Color.GREEN),
    Route(cities=(default_cities["Rostov"], default_cities["Sevastopol"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Rostov"], default_cities["Sochi"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Sevastopol"], default_cities["Sochi"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Sevastopol"], default_cities["Bucharest"]), length=4, color=Color.WHITE),
    Route(cities=(default_cities["Constantinople"], default_cities["Sevastopol"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Constantinople"], default_cities["Angora"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Constantinople"], default_cities["Smyrna"]), length=2, color=Color.NEUTRAL),
    Route(cities=(default_cities["Constantinople"], default_cities["Sofia"]), length=3, color=Color.BLUE),
    Route(cities=(default_cities["Constantinople"], default_cities["Bucharest"]), length=3, color=Color.YELLOW),
    Route(cities=(default_cities["Angora"], default_cities["Smyrna"]), length=3, color=Color.ORANGE),
    Route(cities=(default_cities["Angora"], default_cities["Erzurum"]), length=3, color=Color.BLACK),
    Route(cities=(default_cities["Erzurum"], default_cities["Sevastopol"]), length=4, color=Color.NEUTRAL),
    Route(cities=(default_cities["Erzurum"], default_cities["Sochi"]), length=3, color=Color.RED),
    # TODO: complete this list, items above are correct but the list is not finished.
)
